### ISSUE TITLE
可以挂载家庭云吗？

### ISSUE THREAD

**Issue by star112** [txperl/JustList#1]

**Comment by star112** [comment]
添加一下挂载家庭云

**Comment by txperl** [comment]
目前仅能挂载天翼云盘和 OneDrive，如果测试下来以天翼云盘的方式无法挂载的话，那就是不能了。

抱歉，暂时无意向添加家庭云支持。一是因为受众较小，不能确定体验如何；二是因为天翼云盘的限制直链措施，不禁让我猜测在天翼其他产品中可能也有类似情况。
