### ISSUE TITLE
天翼云盘的解析失效了，返回了个Have no File.的代码

### ISSUE THREAD

**Issue by qiritao** [txperl/JustList#13]
天翼云盘的解析失效了，返回了个Have no File.的代码
我还以为是我这边的问题，看了一下你的演示站也是一样。
麻烦修复一下哦~

**Comment by txperl** [comment]
演示站的天翼云盘又可以正常使用了，貌似好了？

**Comment by qiritao** [comment]
= =......你不知道哪里出问题了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Trii ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 凌晨0:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [txperl/JustList] 天翼云盘的解析失效了，返回了个Have no File.的代码 (#13)





 
演示站的天翼云盘又可以正常使用了，貌似好了？

**Comment by txperl** [comment]
不好意思，我后台的日志文件中没有相关报错，错误出现期间我没有调试，所以不是很清楚是哪方面原因导致的。

如果你有当时的错误来源信息，希望能提供一下，可以帮助我找到问题。

感谢。

**Comment by macreee** [comment]
> 不好意思，我后台的日志文件中没有相关报错，错误出现期间我没有调试，所以不是很清楚是哪方面原因导致的。
> 
> 如果你有当时的错误来源信息，希望能提供一下，可以帮助我找到问题。
> 
> 感谢。
我这边也是。显示这个错误。目测那边接口失效了。不过我半年没更新代码了。我更新一下试试看。
![image](https://user-images.githubusercontent.com/21139951/114049208-d97cae80-98bd-11eb-9dad-eb6d5ea0a59d.png)

**Comment by txperl** [comment]
> > 不好意思，我后台的日志文件中没有相关报错，错误出现期间我没有调试，所以不是很清楚是哪方面原因导致的。
> > 如果你有当时的错误来源信息，希望能提供一下，可以帮助我找到问题。
> > 感谢。
> 
> 我这边也是。显示这个错误。目测那边接口失效了。不过我半年没更新代码了。我更新一下试试看。
> ![image](https://user-images.githubusercontent.com/21139951/114049208-d97cae80-98bd-11eb-9dad-eb6d5ea0a59d.png)

我这边天翼云盘没有问题。

可能是同 IP 短时间内请求同一账号的下载次数太多，被天翼云盘那边限制了？可以试一下换成其他账号，或者在其他 IP 下跑跑看。如果还有问题请反馈...

近期会有一些更新，其中会继续完善报错机制的。

**Comment by macreee** [comment]
> > > 不好意思，我后台的日志文件中没有相关报错，错误出现期间我没有调试，所以不是很清楚是哪方面原因导致的。
> > > 如果你有当时的错误来源信息，希望能提供一下，可以帮助我找到问题。
> > > 感谢。
> > 
> > 
> > 我这边也是。显示这个错误。目测那边接口失效了。不过我半年没更新代码了。我更新一下试试看。
> > ![image](https://user-images.githubusercontent.com/21139951/114049208-d97cae80-98bd-11eb-9dad-eb6d5ea0a59d.png)
> 
> 我这边天翼云盘没有问题。
> 
> 可能是同 IP 短时间内请求同一账号的下载次数太多，被天翼云盘那边限制了？可以试一下换成其他账号，或者在其他 IP 下跑跑看。如果还有问题请反馈...
> 
> 近期会有一些更新，其中会继续完善报错机制的。

---
拉了最新的没问题了。原因定位不到。可能旧版接口那边有点不兼容？log信息太少了。看不太到。我机器倒是没换。看了下访问日志，就我自己身边人进来用了。大概就是旧版没更新导致的吧。

**Comment by txperl** [comment]
> > > > 不好意思，我后台的日志文件中没有相关报错，错误出现期间我没有调试，所以不是很清楚是哪方面原因导致的。
> > > > 如果你有当时的错误来源信息，希望能提供一下，可以帮助我找到问题。
> > > > 感谢。
> > > 
> > > 
> > > 我这边也是。显示这个错误。目测那边接口失效了。不过我半年没更新代码了。我更新一下试试看。
> > > ![image](https://user-images.githubusercontent.com/21139951/114049208-d97cae80-98bd-11eb-9dad-eb6d5ea0a59d.png)
> > 
> > 
> > 我这边天翼云盘没有问题。
> > 可能是同 IP 短时间内请求同一账号的下载次数太多，被天翼云盘那边限制了？可以试一下换成其他账号，或者在其他 IP 下跑跑看。如果还有问题请反馈...
> > 近期会有一些更新，其中会继续完善报错机制的。
> 
> 拉了最新的没问题了。原因定位不到。可能旧版接口那边有点不兼容？log信息太少了。看不太到。我机器倒是没换。看了下访问日志，就我自己身边人进来用了。大概就是旧版没更新导致的吧。

这样啊，之后有时间还是重写下天翼云盘 API 相关的代码吧。谢谢反馈！

**Comment by txperl** [comment]
问题可能是由天翼云盘 Token 过期所导致。在最近版本中已增加防范措施，应该不会再有同样原因的问题了。
