### ISSUE TITLE
天翼网盘无法启动，打开网站空白

### ISSUE THREAD

**Issue by jing5460** [txperl/JustList#16]
![image](https://user-images.githubusercontent.com/38358681/116887050-6a943a80-ac5c-11eb-8f92-2f55a2ef8695.png)
![image](https://user-images.githubusercontent.com/38358681/116887158-8f88ad80-ac5c-11eb-86f3-d8d1f001c792.png)
 
怎么搭建啊

**Comment by txperl** [comment]
程序需要的 Python 依赖包没有安装成功，自己手动安装一下吧。
