### ISSUE TITLE
怎么部署在VPS上？

### ISSUE THREAD

**Issue by kyeo-hub** [txperl/JustList#17]
在VPS上运行了，怎么访问？

**Comment by txperl** [comment]
可以简单把 https://github.com/txperl/JustList/blob/e686e62360157218be9cd8c3b0578e288dc10bdb/main.py#L57 的 `127.0.0.1` 改成 `0.0.0.0`，然后通过 `{服务器 IP}:5000` 访问。

如果需要通过域名访问，可以安装 NGINX，网上有很多配置教程。搜索关键词可以参考 “nginx python flask”。

**Comment by kyeo-hub** [comment]
谢谢，另外还有文件夹一多，就显示不了的问题是什么原因呢？

**Comment by txperl** [comment]
程序会一次性加载全部允许的文件并缓存，所以若文件较多此过程可能会较慢（取决于你文件的数量与网络状况），但不影响正常运行。如果第一次启动还没加载就访问网页的话，就会一片空白。可以等几分钟刷新一下前端网页。

**Comment by kyeo-hub** [comment]
谢谢指教！

**Comment by kyeo-hub** [comment]
已经部署到VPS上了，但是始终

**Comment by kyeo-hub** [comment]
我尝试了一下SSH到服务器执行`python main.py`得到结果`[cloud189] token error, try to login`

**Comment by txperl** [comment]
> 我用的宝塔面板python项目管理器插件，已经部署到VPS上了，但是始终刷新不出来文件夹，设置在本地却没有问题，恕我愚笨。

刷新不出文件夹可能是加载的时候被排除掉了？可以看看自己的配置项。

https://github.com/txperl/JustList/blob/e686e62360157218be9cd8c3b0578e288dc10bdb/app/config/cloud189.yml#L26

**Comment by txperl** [comment]
> 我尝试了一下SSH到服务器执行`python main.py`得到结果`[cloud189] token error, try to login`

这是因为可能 IP 变化或是超过一定时间，之前的 Token 就失效了，程序会自动通过账号密码尝试登陆。这是正常的。
