### ISSUE TITLE
如果cloud189.yml 配置的 cant_enterFolder 留空 , 提示'NoneType' object is not iterable     End

### ISSUE THREAD

**Issue by rubnet** [txperl/JustList#18]
[cache] running
Error at 2021-06-09 18:56:57:
'NoneType' object is [not iterable](https://github.com/txperl/JustList/blob/master/app/lib/static/util.py#L101
)                                 End;

**Comment by rubnet** [comment]
cant_visFile 留空，则所有文件无法显示

**Comment by txperl** [comment]
已修复，感谢反馈。
