### ISSUE TITLE
我想说家庭云也是天翼云盘，只是要移动端ua才显示。外加一个family id

### ISSUE THREAD

**Issue by star112** [txperl/JustList#2]
天翼云盘里的家庭云有1T的空间，个人云只有30G。
https://github.com/reruin/sharelist/blob/master/plugins/drive.189cloud.home.js可以参考下

**Comment by star112** [comment]
![QQ截图20200901194426](https://user-images.githubusercontent.com/63368487/91845381-a1f4b680-ec8b-11ea-9ca6-1b6d082d81ae.png)

**Comment by txperl** [comment]
但 API 可能不同。

我之后看一下，如果只需要小部分修改就添加家庭云支持。
