### ISSUE TITLE
问题：【: ( 数据获取失败... 刷新页面或点击按钮以重试】

### ISSUE THREAD

**Issue by 508044570** [txperl/JustList#21]
按流程弄完后，打开网站首页提示这个，请问下是什么原因
![image](https://user-images.githubusercontent.com/20151745/121786289-82fb5b80-cbf1-11eb-93f1-b3a62e4c78d4.png)

**Comment by txperl** [comment]
与后端请求失败或者数据错误，具体可以打开「开发者工具-网络」查看具体原因。

**Comment by 508044570** [comment]
> 与后端请求失败或者数据错误，具体可以打开「开发者工具-网络」查看具体原因。

请求400
![image](https://user-images.githubusercontent.com/20151745/121793322-8d891580-cc30-11eb-97da-50a4efa6c227.png)

**Comment by txperl** [comment]
看了一下，返回 `no method`。检查一下自己 `switch.yml` 是否配置正确。

**Comment by 508044570** [comment]
> 看了一下，返回 `no method`。检查一下自己 `switch.yml` 是否配置正确。

也试过只配置本地存储的方式，也是不行，都提示这个
![image](https://user-images.githubusercontent.com/20151745/121793751-f2466f00-cc34-11eb-88d6-c753d720bbf3.png)
![image](https://user-images.githubusercontent.com/20151745/121793760-fa9eaa00-cc34-11eb-82a0-5c242fb9b64b.png)
![image](https://user-images.githubusercontent.com/20151745/121793778-12762e00-cc35-11eb-80f8-9db0cb238158.png)

**Comment by txperl** [comment]
目前程序只有一处会报 `no method` 的错误。

https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/altfe/handle.py#L22

也就是在指令选择部分出错了，与具体功能模块无关。但正常情况下，这部分应该是不会出错的... 要不你把程序完整替换一下，再跑一下看看？

**Comment by 508044570** [comment]
> 目前程序只有一处会报 `no method` 的错误。
> 
> https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/altfe/handle.py#L22
> 
> 也就是在指令选择部分出错了，与具体功能模块无关。但正常情况下，这部分应该是不会出错的... 要不你把程序完整替换一下，再跑一下看看？

emmm......还是不行

**Comment by txperl** [comment]
本地有什么报错信息吗？

**Comment by kyeo-hub** [comment]
我又来了 #17  
上次VPS部署成功后，不小心毁掉了自己的Oracle VPS，关于JustList的记录blog都毁掉了，本地无备份。这次还是同样的问题来的。
- 本地部署成功。
![image](https://user-images.githubusercontent.com/44312958/124864322-4c93df00-dfeb-11eb-95e8-743a2100dd15.png)
![image](https://user-images.githubusercontent.com/44312958/124864410-6f25f800-dfeb-11eb-889d-429eca9c5e63.png)

- VPS部署同楼主一样报错```{"code":0,"msg":"no method"}```
![image](https://user-images.githubusercontent.com/44312958/124864588-c4620980-dfeb-11eb-992e-9521a5f9621b.png)
![image](https://user-images.githubusercontent.com/44312958/124864661-e65b8c00-dfeb-11eb-8a38-a53304572d07.png)

**Comment by txperl** [comment]
> 我又来了 #17
> 上次VPS部署成功后，不小心毁掉了自己的Oracle VPS，关于JustList的记录blog都毁掉了，本地无备份。这次还是同样的问题来的。
> 
> * 本地部署成功。
>   ![image](https://user-images.githubusercontent.com/44312958/124864322-4c93df00-dfeb-11eb-95e8-743a2100dd15.png)
>   ![image](https://user-images.githubusercontent.com/44312958/124864410-6f25f800-dfeb-11eb-889d-429eca9c5e63.png)
> * VPS部署同楼主一样报错`{"code":0,"msg":"no method"}`
>   ![image](https://user-images.githubusercontent.com/44312958/124864588-c4620980-dfeb-11eb-992e-9521a5f9621b.png)
>   ![image](https://user-images.githubusercontent.com/44312958/124864661-e65b8c00-dfeb-11eb-8a38-a53304572d07.png)

方便提供一下运行地址吗？如果不愿意公开的话，可以通过[邮箱](https://biu.tls.moe/#/lib/dl?id=%e5%8f%8d%e9%a6%88%e3%80%81%e5%85%88%e8%a1%8c%e4%bd%93%e9%aa%8c)发给我。

**Comment by kyeo-hub** [comment]
不好意思，我的网络打开github有些神经质。所以现在才看到留言。
昨天后来对比了**CTlist**，**PanIndex**后，采用了**PanIndex**。周末要带娃，改天再尝试，发地址给你。

**Comment by txperl** [comment]
好的。被你这么一说，我去看了一下 PanIndex，前端好像 JustList 啊？hhh。

**Comment by kyeo-hub** [comment]
你看他的`PanIndex`设置页面吗，配置起来非常简单。不过**Go**我不太熟悉，**Python**我还自己看了点就是。测试地址已经发给你邮箱了 @txperl 你去看看吧。

**Comment by kyeo-hub** [comment]
> 其实我自认为 JustList 配置起来也挺简单的... 之后会简化部分初始化操作的，到时候也会支持 Docker 构建的。

是的，JustList配置起来也是非常简单的，只是对于小白来说，需要去不同的文件修改参数，没有一个设置页面，所以感觉很困惑。
好了，回到主题，你看过我给的地址没有？帮助我这种小白来看看问题所在。

**Comment by txperl** [comment]
> > 其实我自认为 JustList 配置起来也挺简单的... 之后会简化部分初始化操作的，到时候也会支持 Docker 构建的。
> 
> 是的，JustList配置起来也是非常简单的，只是对于小白来说，需要去不同的文件修改参数，没有一个设置页面，所以感觉很困惑。
> 好了，回到主题，你看过我给的地址没有？帮助我这种小白来看看问题所在。

确实，部分配置参数看着确实比较麻烦。

看到了，你可以看一下我的回复... 如果能提供一下运行环境、系统以及 Python 版本号的信息就好了。
