### ISSUE TITLE
新标签打开

### ISSUE THREAD

**Issue by iocoeoqq** [txperl/JustList#23]
打开文件，能新标签打开吗。因为返回列表又开始从第一个开始下滑，比较不好找文件

**Comment by txperl** [comment]
这个很容易自己实现。

只需判断为文件时，将下面这段代码的点击事件修改为在新标签页打开网址即可。当然，也可以简单添加 `<a target="_blank">` 标签，但不推荐这种方法。

https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/templates/md.html#L209-L212

**Comment by iocoeoqq** [comment]
大佬，我不太懂代码，能给写一段我改上去吗
