### ISSUE TITLE
我按教程配置完成后 只有本地能访问是为什么呀

### ISSUE THREAD

**Issue by Cccasual** [txperl/JustList#24]

**Comment by txperl** [comment]
因为程序默认的监听地址是 `127.0.0.1`，这是一段回送地址，即本地域内的。如果没有配置相关 HTTP 服务器，外部是无法访问的。

如果需要外部访问，具体方法可以参考这条 Issues：https://github.com/txperl/JustList/issues/17#issuecomment-853992218 。
