### ISSUE TITLE
怎样把多个天翼账号集合到一起，而不是每个网盘都单列自己的文件？

### ISSUE THREAD

**Issue by 889098** [txperl/JustList#25]
网盘一有文件夹1,2,3，网盘二有4,5,6，
怎样让user1下面有文件夹1,2,3,4,5,6，即把两个网盘整合在一起显示？

**Comment by txperl** [comment]
目前只有修改程序代码可以实现。

比较简单的大体思路：在加载各用户（user）文件时，将不同用户（user）的文件以及私密文件夹密码强制合并存入同一用户。即修改下面代码段的 `80-81` 行。

https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/app/lib/core/cloud189/main.py#L69-L86

**Comment by 889098** [comment]
> 目前只有修改程序代码可以实现。
> 
> 比较简单的大体思路：在加载各用户（user）文件时，将不同用户（user）的文件以及私密文件夹密码强制合并存入同一用户。即修改下面代码段的 `80-81` 行。
> 
> https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/app/lib/core/cloud189/main.py#L69-L86

俺不会啊，大佬不能更新修改下吗？

**Comment by txperl** [comment]
这并不是一个 BUG。不过这是一个不错的想法，之后可能会加入的。
