### ISSUE TITLE
怎样添加文件类型的图标?

### ISSUE THREAD

**Issue by 889098** [txperl/JustList#26]
[https://z3.ax1x.com/2021/06/25/RlTeTf.jpg](url)
如图所示，只有zip格式的有个图标，其他的都没有，怎么根据文件类型添加上一些图标？

**Comment by txperl** [comment]
https://github.com/txperl/JustList/blob/c5791e47550ae822de04e4c6fdde5c878910411c/templates/md.html#L347-L354

按照 `"格式名": ["MDUI 对应的 ICON 代码", "文件格式1", "文件格式2"]` 这样的规则添加。

其中，MDUI 对应的 ICON 代码在这里查看：https://www.mdui.org/docs/material_icon 。
