### ISSUE TITLE
list 空白

### ISSUE THREAD

**Issue by ywzhaiqi** [txperl/JustList#30]
docker、本地都试了，`/api/get/list/` 内容为
```json
{"code":1,"msg":{}}
```

**Comment by txperl** [comment]
运行后有提示`... list updated`吗？

**Comment by ywzhaiqi** [comment]
没有

**Comment by ywzhaiqi** [comment]
天翼云盘运行10个小时候，还没 list，还有好多个文件夹内容更多。这也太慢了吧

**Comment by txperl** [comment]
如果网盘文件夹较多的话，暂时不建议用 JustList... 目前只支持启动时把文件目录全部缓存，并且之后刷新缓存时也要重新获取，如果文件夹太多基本属于不能用的。（（

**Comment by ywzhaiqi** [comment]
好吧。
