### ISSUE TITLE
阿里云盘挂载

### ISSUE THREAD

**Issue by cyvyc** [txperl/JustList#34]
阿里云盘应该怎么挂上去 百度过了 (小白的问题)

**Comment by cyvyc** [comment]
refreshToken 应该怎么放上去 一直搞不明白

**Comment by txperl** [comment]
根据程序提示拿到 code 之后，直接复制粘贴到程序等待输入的那一行。

**Comment by cyvyc** [comment]
能给个联系方式吗？

**Comment by txperl** [comment]
直接在这里说吧，如果别人有类似问题也能有个参考。

**Comment by Sakuraciyuan** [comment]
[阿里云盘@10566267b6f448f99db06ffe032b2a8d] 根据此网址「https://media.cooluc.com/decode_token/」的方法获取 Refresh Token 或 BizExt 以登录
Refresh_Token or BizExt: Traceback (most recent call last):
  File "/www/wwwroot/wangpan.com/main.py", line 49, in <module>
    bridge.bridgeInit().run(hint=True)
  File "/www/wwwroot/wangpan.com/altfe/bridge.py", line 32, in run
    classRoot.instantiate(["LIB_CORE", "PRE"])
  File "/www/wwwroot/wangpan.com/altfe/interface/root.py", line 57, in instantiate
    cls.__MODULE[key][name] = cls.__MODULE[key][name]()
  File "/www/wwwroot/wangpan.com/app/lib/core/aliyundrive/main.py", line 18, in __init__
    self.auto()
  File "/www/wwwroot/wangpan.com/app/lib/core/aliyundrive/main.py", line 27, in auto
    _input = str(input(f"Refresh_Token or BizExt: ").strip())
EOFError: EOF when reading a line``

**Comment by Sakuraciyuan** [comment]
请问这个怎么弄呀，获取的都不一样，填了就502，本人小白

**Comment by txperl** [comment]
照着那个网址里的方法获取就好了，是每次都不一样的。

**Comment by Sakuraciyuan** [comment]
可是填写后就访问不了，显示502

**Comment by Sakuraciyuan** [comment]
试了很多次，只要填写阿里云的那个就502删掉就可以访问

**Comment by txperl** [comment]
你填入的是按通过网页解析出来的东西吗？还是获取到 bizcode 就直接填入了。如果步骤没错的话，两者都行的。

你可以试一下把那些字符串先粘贴到任意一个文本编辑器中，从中复制，然后填入程序。

**Comment by Sakuraciyuan** [comment]
右键复制的响应，然后解码，粘贴进去的

**Comment by Sakuraciyuan** [comment]
昨天有二次验证，改了密码后就没了
是不是这个原因呀

**Comment by txperl** [comment]
只要能拿到 bizext 那登录应该是没问题的。报错显示是程序读取输入（输入字符到程序）的问题，所以可能规范下输入格式或者换个终端试试？

**Comment by Sakuraciyuan** [comment]
...还是不会

**Comment by Sakuraciyuan** [comment]
重新装了下还是一样的

**Comment by Sakuraciyuan** [comment]
填阿里云的就访问不了

**Comment by Sakuraciyuan** [comment]
# 阿里云盘配置项

accounts:
   - "ad0b444d352c433983cbbf0600cfbee2"
  # 阿里云盘账号
  # 可输入多组账号，但自定义名称不可相同
  # 程序启动时会引导您手动获取 Refresh Token
  #
  # 请参考如下格式填写：
  # - "<自定义名称>"
  #
  # 例子：
  # - "AliyunDrive_A"
  # - "AliyunDrive_B"

**Comment by Sakuraciyuan** [comment]
我这样填对么

**Comment by Sakuraciyuan** [comment]
可以加你好友帮忙填吗

**Comment by Sakuraciyuan** [comment]
# 阿里云盘配置项

accounts:
   - "Refresh Token"

**Comment by Sakuraciyuan** [comment]
用的宝塔，还有软件商店里的Python项目管理器

**Comment by Sakuraciyuan** [comment]
不会启动呀，第一次弄这个

**Comment by Sakuraciyuan** [comment]
能不能给个联系方式我截图给你，帮忙看下吖

**Comment by txperl** [comment]
> 用的宝塔，还有软件商店里的Python项目管理器

那我知道原因了... 是因为初次启动程序需要手动输入 Code，而那个项目管理器好像不会以交互形式启动程序，因此无法输入 Code。仅启用天翼云盘是不需要手动输入东西的，一旦启用 OneDrive 或阿里云盘就会需要。

建议使用按照 [Docker 部署方法](https://hub.docker.com/r/txperl/justlist)进行配置，或者就直接用根据 [README](https://github.com/txperl/JustList/blob/5c3a400f548d122e2e3a78e2d2d8bdef5c41314b/README.md?plain=1#L20-L82) 手动部署。

**Comment by txperl** [comment]
> 能不能给个联系方式我截图给你，帮忙看下吖

先试一下我上面说的方法吧。

**Comment by Sakuraciyuan** [comment]
大佬，我还是不会，完全不会用，

**Comment by Sakuraciyuan** [comment]
`  File "main.py", line 5, in <module>
    from flask import Flask, jsonify, render_template
ImportError: No module named fla`

**Comment by txperl** [comment]
> ` File "main.py", line 5, in <module> from flask import Flask, jsonify, render_template ImportError: No module named fla`

要先安装 Python 依赖。

```python
pip install -r requirements.txt
```

**Comment by Sakuraciyuan** [comment]
谢谢大佬！！1感谢感谢，已经OK了

**Comment by Sakuraciyuan** [comment]
![image](https://user-images.githubusercontent.com/95675298/148352931-05892425-f70b-4ec3-9d8b-355143f32eb6.png)

**Comment by Sakuraciyuan** [comment]
大佬输入了没变诶，网站没变诶

**Comment by Sakuraciyuan** [comment]
![@ISUVR3RMV@W0}OW7LB5SXV](https://user-images.githubusercontent.com/95675298/148354140-64c6ad78-4565-4021-a5b2-4e55b145b6b2.png)

**Comment by txperl** [comment]
> ![image](https://user-images.githubusercontent.com/95675298/148352931-05892425-f70b-4ec3-9d8b-355143f32eb6.png)
> 
> 

这是因为程序运行需要的端口被占用了，改一下 `sys.host` 就好了。

**Comment by txperl** [comment]
> ![@ISUVR3RMV@W0}OW7LB5SXV](https://user-images.githubusercontent.com/95675298/148354140-64c6ad78-4565-4021-a5b2-4e55b145b6b2.png)
> 
> 

这应该算是没什么问题了吧... 能正常使用吗？不能的话，看一下之后有没有显示 `xxx list updated`，或看一下 `./app/config/` 中有没有 `.token` 文件夹。

**Comment by Sakuraciyuan** [comment]
有这个

> > ![@ISUVR3RMV@W0}OW7LB5SXV](https://user-images.githubusercontent.com/95675298/148354140-64c6ad78-4565-4021-a5b2-4e55b145b6b2.png)
> 
> 这应该算是没什么问题了吧...能正常使用吗？不能的话，看一下之后有没有显示 ，或看一下 中有没有 文件夹。`xxx list updated``./app/config/``.token`

有这个，就是不显示用户名

**Comment by Sakuraciyuan** [comment]
用户切换那里没有

**Comment by txperl** [comment]
> 用户切换那里没有
> 
> 

点一下网页上的刷新按钮（用户名下方）看看。

**Comment by Sakuraciyuan** [comment]
都试了

**Comment by Sakuraciyuan** [comment]
我不知道怎么弄了，我把ip账号密码给你吧， 你来试试

**Comment by Sakuraciyuan** [comment]
![{QS4_L)NHPCU`J%O424Q0%X](https://user-images.githubusercontent.com/95675298/148367079-2e52eec9-c580-4a26-b586-615d7b8f17d7.png)
![3$MM_0%`DF @O`8I_H 7 @C](https://user-images.githubusercontent.com/95675298/148367084-d27c28bc-c31b-4635-84fe-8fccffec3a70.png)
![OVT Z%HRS6R{O4RMSAJ1AH6](https://user-images.githubusercontent.com/95675298/148367094-f2f55724-2680-4e81-bf19-a390e3b16e0d.png)

**Comment by Sakuraciyuan** [comment]
![{QS4_L)NHPCU`J%O424Q0%X](https://user-images.githubusercontent.com/95675298/148367154-969af615-a75f-4e89-909d-a91840fb65ef.png)

**Comment by Sakuraciyuan** [comment]
> > 我不知道怎么弄了，我把ip账号密码给你吧， 你来试试
> 
> 你通过邮件发给我吧。（（

发过去了
