### ISSUE TITLE
账号填写不是那么明确，挂的Onedrive试了好多组合都是开启之后没有获取刷新toke，能写一下onedrive账号的具体填写吗

### ISSUE THREAD

**Issue by nameyou486** [txperl/JustList#36]
我试了
```
admin@xxx.onmicrosoft.com: 0
我要显示的名称: admin@xxx.onmicrosoft.com 0
我要显示的名称: 0
```
还是没明白是什么规范

**Comment by txperl** [comment]
就如你的例子，当填写 `admin@xxx.onmicrosoft.com: 0` 时，会以 `admin@xxx.onmicrosoft.com` 为你的 JustList 昵称，`0` 则代表是 OneDrive 国际版。

注意，只是昵称（显示在网页上的），与你想绑定的 OneDrive 账号没有任何关系。

“没有获取刷新 token” 具体是什么意思？可以展示一下程序启动后的提示消息吗？

**Comment by nameyou486** [comment]
这是我的操作流程，您看一下是我的操作哪里错了吗。
视频链接：[link](https://www.coludxyy.top/cloud2/%E6%9D%82/QQ%E5%BD%95%E5%B1%8F20220219211104.mp4?preview)

**Comment by nameyou486** [comment]
这是我的操作流程，您看一下是我的哪里出错了。
视频link：[link](这是我的操作流程，您看一下是我的哪里出错了。)

**Comment by txperl** [comment]
> 这是我的操作流程，您看一下是我的哪里出错了。
> 
> 视频link：[link](这是我的操作流程，您看一下是我的哪里出错了。)

链接指向 localhost...

**Comment by nameyou486** [comment]
抱歉，我的失误，现在可以了。

**Comment by txperl** [comment]
你没有缩进... 在用户昵称 `onedrive` 加两个空格就可以了。

**Comment by nameyou486** [comment]
啊这，就这么。。。。好吧，麻烦您了，您做的搜索功能很好。
