### ISSUE TITLE
似乎设置密码了不起作用

### ISSUE THREAD

**Issue by hcllmsx** [txperl/JustList#37]
![Snipaste_2022-03-17_13-37-32](https://user-images.githubusercontent.com/63240764/158744425-464b1538-ccb3-44c3-a7f2-ca991ea0e7e1.png)
就像这样，我上传了，去刷新了，点进去依然不用输入密码。
然后不知道一顿什么操作，好像有要输入密码了。于是我去输入密码，就一直提示我密码错误（我直接复制文件名去掉._.jl之后的字符应该就是密码吧？然而一直提示我错误。我也点了那个刷新按钮了。）

另外再提个建议，这个密码输入的时候，虽然错误，但我刷新了之后，浏览器还是会提示我是否要保存密码。
我在想，如果我密码是对的，又或者有好几个文件夹都设了密码，那它提示我保存的密码感觉没啥用。
不妨输入密码的时候，直接明文显示出来，进去之后，也不会提示你保存。

最后想问一下，这个有交流群吗？

**Comment by txperl** [comment]
我今晚试一下，感谢反馈。

**Comment by txperl** [comment]
##### 第一个问题
刚刚试了一下。同样创建了 `H95piCL._.jl` 作为密码标识文件，然后没什么问题...

请问你更改完这个文件后，重新启动程序了吗？程序必须重新刷新缓存才能正确启用密码。

##### 第二个问题
这个确实是部分浏览器的问题，识别到输入框的种类为密码就会要求保存。

我会在下一次更新中改善这种情况，应该可以解决。

暂时没有交流群...

**Comment by hcllmsx** [comment]
我今天折腾一天了，emmm，关于密码的问题我搞明白了。然后那个什么“前后端分离”和“强制刷新目录缓存”硬是没弄明白。还有/app/config/下的cloud189.yml我尝试配置了“加载目录时排除的文件夹名”和“加载目录时排除的文件名”和“rootPath”这三个，貌似都没啥卵用.....不知道是哪里没操作对。我还想搞明白了，弄个文字教程发我博客或者弄个视频教程啥的，结果自己一天了，也没整明白，......hah，留下了菜鸡的泪水

**Comment by txperl** [comment]
是我文档描述得不够清楚，之后会慢慢完善的。

如果你有很多想搞清楚的，可以在这慢慢询问，或者通过[这里](https://biu.tls.moe/#/lib/dl?id=%e5%8f%8d%e9%a6%88%e3%80%81%e5%85%88%e8%a1%8c%e4%bd%93%e9%aa%8c)的其中一个方式，我会逐个解答的。

**Comment by txperl** [comment]
##### 前后端分离
这个最简单的应用就是：后端部署在一个服务器，而前端页面可以放在相同或其他任意平台。与后端的交互都是通过 API 进行的，所以在通讯方面具有覆盖性。

具体你可以搜索一下它的解释，会比我说的好很多。

##### 强制刷新目录缓存
由于程序会定时对所有目录进行缓存，所以在这个时间区间内，如果你的网盘文件发生了变动，那程序是无法立即做出更新的。

所以需要强制刷新目录缓存，手动刷新程序的缓存，以与最新的网盘目录同步。

##### 配置项
如果正确设置的话应该是有用的，可能是你的配置文件格式写错了？
