### ISSUE TITLE
如何更新缓存，更换天翼云盘的账号后还是显示之前账号的列表

### ISSUE THREAD

**Issue by ekeyst** [txperl/JustList#38]
“编辑 ./app/plugin/sys_update.py ，将 sys/update/xxxiiixxx 改为你想要的强制刷新地址"
这个不理解
1.这个是可以解决无法自动更新缓存的问题吗？
2.”改为你想要的强制刷新地址”，修改成什么地址？

**Comment by txperl** [comment]
如果是修改了 `config.yml` 相关的配置文件，只能通过重启程序来应用。

程序会根据配置中的缓存刷新间隔来自动刷新，这里会被更新的只是已启动的网盘文件列表。

如果想要立即刷新，那只能通过 `sys_update` 插件来手动请求刷新。至于修改成什么地址，随便的一串密码都可以，只是为了防止被恶意请求的。设置完后，访问 `https://{域}/sys/update/{你设置的值}` 就能手动刷新了。

**Comment by ekeyst** [comment]
> 如果是修改了 `config.yml` 相关的配置文件，只能通过重启程序来应用。
> 
> 程序会根据配置中的缓存刷新间隔来自动刷新，这里会被更新的只是已启动的网盘文件列表。
> 
> 如果想要立即刷新，那只能通过 `sys_update` 插件来手动请求刷新。至于修改成什么地址，随便的一串密码都可以，只是为了防止被恶意请求的。设置完后，访问 `https://{域}/sys/update/{你设置的值}` 就能手动刷新了。

完全没用。。
按你的提示，设置了sys_update，然后显示这个 
{"code":0,"msg":"no method"}

重装一次的确可以解决显示之前账号列表的问题。
另外，看到config下面的.toke.json有两个盘的信息，但是打开列表两个盘却只能显示一个盘。。
问题有点多。。

**Comment by txperl** [comment]
第一个问题，这个结果说明你访问了错误的地址，与后台设置的不匹配。如果不提供更多信息，我也无能为力。

第二个问题，请确保自己前端页面已刷新缓存，或是后端网络正常并正确获取到了网盘文件列表，提示了 `list updated`。

**Comment by ekeyst** [comment]
> 第一个问题，这个结果说明你访问了错误的地址，与后台设置的不匹配。如果不提供更多信息，我也无能为力。
> 
> 第二个问题，请确保自己前端页面已刷新缓存，或是后端网络正常并正确获取到了网盘文件列表，提示了 `list updated`。

设置的是这个
<img width="324" alt="微信图片_20220419134807" src="https://user-images.githubusercontent.com/71384336/163928738-b0633505-7eea-44b6-9680-cd5baefda002.png">

页面结果
<img width="318" alt="微信图片_20220419134825" src="https://user-images.githubusercontent.com/71384336/163929953-8ea9e081-7436-4728-be27-2f9e5f4a9eb3.png">

用的是隐私模式，页面输入https://{域}/sys/update/{你设置的值}后，是400
<img width="470" alt="微信图片_20220419134903" src="https://user-images.githubusercontent.com/71384336/163932034-12fee0b4-fd05-40f8-99c4-3aed1794121a.png">

两个盘不能同时出现
<img width="234" alt="微信图片_20220419134908" src="https://user-images.githubusercontent.com/71384336/163932545-e45723e3-a53a-4150-b3aa-4fef23d99ffb.png">

**Comment by txperl** [comment]
**Q1**

如果只填写了 `xxx`，那只须访问 `https://{域}/xxx` 即可。`...{域}/{something}` 中 `{something}` 的内容是跟你 `bind` 的内容完全一致的。例如：

- `bind s1` 则访问 `https://{域}/s1`
- `bind api/sys/update/s3` 则访问 `https://{域}/api/update/s3`
- `bind api/sys/update/s4/` 则访问 `https://{域}/api/update/s4/`

**Q2**

你点击一下用户名左侧的图标可以切换至其他网盘。

**Comment by ekeyst** [comment]
> **Q1**
> 
> 如果只填写了 `xxx`，那只须访问 `https://{域}/xxx` 即可。`...{域}/{something}` 中 `{something}` 的内容是跟你 `bind` 的内容完全一致的。例如：
> 
> * `bind s1` 则访问 `https://{域}/s1`
> * `bind api/sys/update/s2` 则访问 `https://{域}/api/update/s2`
> * `bind api/sys/update/s3/` 则访问 `https://{域}/api/update/s3/`
> 
> **Q2**
> 
> 你点击一下用户名左侧的图标可以切换至其他网盘。

1.我重试了一下https://{域}/xxx，还是返回 {"code":0,"msg":"no method"} 
这个是什么问题呢？正确应该是 code:"1" 吧？

2.嗯，点那个头像看到其他盘了，我之前一直点189pan那里，因为是连在一起的，没有提示。。

**Comment by txperl** [comment]
请问有没有启用此插件？参考 README 中的第二步。

https://github.com/txperl/JustList/blob/7112d6ea39b87005f692350e2ee9d7f6aa6126f4/README.md?plain=1#L120-L127

**Comment by ekeyst** [comment]
> 请问有没有启用此插件？参考 README 中的第二步。
> 
> https://github.com/txperl/JustList/blob/7112d6ea39b87005f692350e2ee9d7f6aa6126f4/README.md?plain=1#L120-L127

已经开了，但还是返回{"code":0,"msg":"no method"}
所以很奇怪

**Comment by txperl** [comment]
我本地没什么问题。可以再把配置内容和访问地址截个图看一下吗？

**Comment by ekeyst** [comment]
config下的cloud189.yml
<img width="326" alt="微信图片_20220420215556" src="https://user-images.githubusercontent.com/71384336/164247835-c3f4295b-025e-4134-8e61-3c495499eb24.png">


switch.yml
<img width="344" alt="微信截图_20220420215717" src="https://user-images.githubusercontent.com/71384336/164247758-8acd08b8-9551-4a75-b23b-6a5b4c06b9e3.png">

plugin下的sys_update.py
<img width="358" alt="微信截图_20220420215741" src="https://user-images.githubusercontent.com/71384336/164248370-4e6bd235-f0cc-40b4-8eb3-92883473442d.png">

页面输出结果
<img width="253" alt="微信截图_20220420215840" src="https://user-images.githubusercontent.com/71384336/164248462-7312a6e6-91c0-4236-b1a1-d00f4b6cef63.png">

**Comment by txperl** [comment]
不好意思过了这么久才回复。

我本地根据你的配置运行了一下，插件是可以正常运行的... 这样配置理论上也是没问题的。请问你修改配置后重启程序了吗？
