### ISSUE TITLE
天翼云超过1G文件返回Have no file.

### ISSUE THREAD

**Issue by qinlili23333** [txperl/JustList#39]
小于1G的文件一切正常，超过1G都返回Have no file.
可提供一个15G文件供测试：https://cloud.189.cn/web/share?code=fUFfuqvuE7va（访问码：rl2x）

**Comment by txperl** [comment]
感谢反馈，已修复。

原因是原本使用的 v1 API 无法下载大尺寸文件，现在将 v2 API 设置为了备用方法。
