### ISSUE TITLE
阿里云盘添加出现问题

### ISSUE THREAD

**Issue by imgblz** [txperl/JustList#40]
[Altfe] ;)
[cache] running
[阿里云盘@AliyunDrive] 根据此网址「https://media.cooluc.com/decode_token/」的方法获取 Refresh Token 或 BizExt 以登录
Refresh_Token or BizExt: Traceback (most recent call last):
  File "/www/wwwroot/JustList-master/main.py", line 49, in <module>
   [Altfe] ;)
[cache] running
[阿里云盘@AliyunDrive] 根据此网址「https://media.cooluc.com/decode_token/」的方法获取 Refresh Token 或 BizExt 以登录
Refresh_Token or BizExt: Traceback (most recent call last):
  File "/www/wwwroot/JustList-master/main.py", line 49, in <module>

**Comment by txperl** [comment]
请问是一运行就这样还是什么情况下才会出现？

**Comment by imgblz** [comment]
一运行就这样，把阿里云的配置删了正常打开，Python3.9的环境

**Comment by txperl** [comment]
阿里云盘的配置删了是把配置文件删除了吗...?

**Comment by imgblz** [comment]
是删除自定义名称这一行

**Comment by txperl** [comment]
可以看一下配置文件吗？

**Comment by imgblz** [comment]
只改了这里
accounts:
  # 阿里云盘账号
  # 可输入多组账号，但自定义名称不可相同
  # 程序启动时会引导您手动获取 Refresh Token
  #
  # 请参考如下格式填写：
  # - "<自定义名称>"
  # 例子：
   - "aliyun"

Trii Hsia ***@***.***> 于2022年8月30日周二 17:02写道：

**Comment by imgblz** [comment]
只改了这里
accounts:
  # 阿里云盘账号
  # 可输入多组账号，但自定义名称不可相同
  # 程序启动时会引导您手动获取 Refresh Token
  #
  # 请参考如下格式填写：
  # - "<自定义名称>"
  # 例子：
   - "aliyun"

**Comment by txperl** [comment]
抱歉才回复... 根据你的配置我测试下来是没有问题的。请问解决了吗？
