### ISSUE TITLE
希望添加Webdav目录挂载

### ISSUE THREAD

**Issue by jerryyang-git** [txperl/JustList#45]
希望支持webdav网盘挂载

**Comment by txperl** [comment]
还没有计划加入 WebDAV 的支持，不好意思。

有很多其他全方面更加优秀的网盘 index 程序支持 WebDAV 的，部署起来也很方便。

暂时抱歉啦。

**Comment by jerryyang-git** [comment]
> 还没有计划加入 WebDAV 的支持，不好意思。
> 
> 有很多其他全方面更加优秀的网盘 index 程序支持 WebDAV 的，部署起来也很方便。
> 
> 暂时抱歉啦。

好的
