### ISSUE TITLE
老哥，怎么通过docker安装，我想装在nas上

### ISSUE THREAD

**Issue by xiaodiaoz** [txperl/JustList#9]
老哥 我在nas里在docke搜索justlist能搜到，但好像不是你的版本。。我也不知道是啥，装也装不了，求老哥整个docker的啊

**Comment by txperl** [comment]
目前没有使用过 NAS，所以不是很清楚你搜到的那个版本是什么... JustList 暂时还没有提供 Docker 镜像，之后会提供的，现在只能你自己做一个了。（（

**Comment by xiaodiaoz** [comment]
😭😭😭&nbsp;&nbsp;明天白天我研究研究怎么做
------&nbsp;原始邮件&nbsp;------
发件人:&quot;Trii&amp;nbsp;Hsia&quot;<notifications@github.com&gt;;
发送时间:2021年2月8日(星期一)&nbsp;晚上10:53
收件人:&quot;txperl/JustList&quot;<JustList@noreply.github.com&gt;;
抄送人:&quot;xiaodiaoz&quot;<318366083@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:Re:&nbsp;[txperl/JustList]&nbsp;老哥，怎么通过docker安装，我想装在nas上&nbsp;(#9)



 
目前没有使用过 NAS，所以不是很清楚你搜到的那个版本是什么... JustList 暂时还没有提供 Docker 镜像，之后会提供的，现在只能你自己做一个了。（（
 
&mdash;

**Comment by txperl** [comment]
可以直接 Pull 一个 Python 镜像，然后把 JustList 源代码下载到本地，照着 README 配一下就好了。

**Comment by txperl** [comment]
过了好久...

如果还需要的话，可以查看 [docker-hub@txperl/justlist](https://hub.docker.com/r/txperl/justlist)。
